development:
   adapter: mysql2
   database: pospulse_development
   username: root
   password:
   host: localhost

test:
   adapter: mysql2
   database: pospulse_test
   username: root
   password: 
   host: localhost

production:
   adapter: mysql2
   database: pospulse_production
   username: root
   password: 
   host: localhost